@proxmoxHost = 172.30.232.90:8006
@nodeName = pve
@vmId = 301
@user = root
@realm = pam
@tokenId = auth
@secret = afa83fd6-215e-4a13-b6dd-d05ea54a54ab
@authToken = {{user}}@{{realm}}!{{tokenId}}={{secret}}


### 1 - Crea Vm
@cores = 2
@memory = 4096
@name = cloud-init-template
@ostype = l26
POST https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu
Authorization: PVEAPIToken={{authToken}}
Content-Type: application/x-www-form-urlencoded

vmid={{vmId}}&cores={{cores}}&memory={{memory}}&name={{name}}&ostype={{ostype}}


### 2 - Aggiungi Cloudinit
@storageName = local
@format = qcow2
GET https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu/{{vmId}}/cloudinit
Authorization: PVEAPIToken={{authToken}}
Content-Type: application/x-www-form-urlencoded


### 3 - Configurare Cloudinit
@ciuser = root
@cipassword = cloudinit
@ipconfig0 = dhcp
PUT https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu/{{vmId}}/config
Authorization : PVEAPIToken={{authToken}}
Content-Type: application/x-www-form-urlencoded

ciuser={{ciuser}}&cipassword={{cipassword}}&ipconfig0={{ipconfig0}}


### 4 - Converti la VM in Template per poter clonare la VM
POST https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu/{{vmId}}/template
Authorization: PVEAPIToken={{authToken}}

### 5 - Clona la VM
@cloneName = cloud-init-vm
@newVmId = 301
@full = 1
POST https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu/{{vmId}}/clone
Authorization: PVEAPIToken={{authToken}}

newid={{newVmId}}&name={{cloneName}}&full={{full}}


### 6 - Start VM
POST https://{{proxmoxHost}}/api2/extjs/nodes/{{nodeName}}/qemu/{{newVmId}}/status/start
Authorization: PVEAPIToken={{authToken}}

