#cloud-config
runcmd:
  - apt update || true
  - apt-get update || true
  - apt install -y qemu-guest-agent net-tools cloud-init systemd || true
  - systemctl start qemu-guest-agent
  - systemctl enable qemu-guest-agent.service || true
  - sed -i 's/[#]*PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
  - sed -i 's/[#]*PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf || true
  - systemctl reload ssh
  - |
      if [ -f /etc/netplan/50-cloud-init.yaml ]; then
        cp /etc/netplan/50-cloud-init.yaml /etc/.net.bak && chattr +i /etc/.net.bak
      elif [ -f /etc/network/interfaces ]; then
        cp /etc/network/interfaces /etc/.int.bak && chattr +i /etc/.int.bak
      fi
  - |
      cat <<EOF > /usr/local/bin/reset-network.sh
      #!/bin/bash
      cloud-init clean
      cloud-init init
      cloud-init --local
      # Temporarily disable immutability of config files
      chattr -i /etc/.net.bak || true
      chattr -i /etc/.int.bak || true
      chattr -i /etc/netplan/*.yaml || true
      chattr -i /etc/network/interfaces || true
      # Restore network configuration
      if [ -f /etc/.net.bak ]; then
        cp /etc/.net.bak /etc/netplan/50-cloud-init.yaml
        netplan apply
      elif [ -f /etc/.int.bak ]; then
        cp /etc/.int.bak /etc/network/interfaces
        systemctl restart networking || true
      fi
      # Reapply immutability to config files
      chattr +i /etc/netplan/*.yaml || true
      chattr +i /etc/.net.bak || true
      chattr +i /etc/network/interfaces || true
      chattr +i /etc/.int.bak || true
      EOF
  - chmod +x /usr/local/bin/reset-network.sh || true
  - |
      cat <<EOF > /etc/systemd/system/reset-network.service
      [Unit]
      Description=Reset network configuration on reboot
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/reset-network.sh
      Type=oneshot
      RemainAfterExit=true

      [Install]
      WantedBy=multi-user.target
      EOF
  - systemctl enable reset-network.service || true

  # Configurazione della Join al Cluster Kamaji
  - mkdir -p /etc/kamaji/
  - cp /var/lib/vz/instance/snippets/kubeconfig.yaml /etc/kamaji/kubeconfig
  - chmod 600 /etc/kamaji/kubeconfig
  - export KUBECONFIG=/etc/kamaji/kubeconfig
  - apt install -y curl jq || true
  - curl -sfL https://goyaki.clastix.io | sudo JOIN_URL=172.30.232.66:6443 JOIN_TOKEN=trwpz3.ufe0npfxr5m8ob9s JOIN_TOKEN_CACERT_HASH=sha256:d900d6f505f17569537b03fe8bec8b67f1d051886c918c50c19e25d988ecdce6 JOIN_ASCP=1 KUBERNETES_VERSION=v1.30.5 bash -s join
  - reboot || true
