@kamajiServer = 172.30.232.61:6443
@tenantTestServer = 172.30.232.66:6443
@accessToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IlFIdVRkcmRSMEZ3cWp6TGVNSEZJQ0VidS1mZlI0YTBBNmlrYXVkUFNqc3MifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQ0MjE0MzQ0LCJpYXQiOjE3NDQyMTA3NDQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiY2JlMWZjYzItNTVkNC00NmVhLWExZjMtZTBkN2E4MjA1YjQ3Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhcGktYWNjZXNzIiwidWlkIjoiMTNjYTM5ZTctOThlZS00YjAzLTk4ZWQtMjQ3MzI4MWM2NTQzIn19LCJuYmYiOjE3NDQyMTA3NDQsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphcGktYWNjZXNzIn0.nBSITlpVn1MZZmVf8AE92mZfXDvArsOK2EIIjg6HencMk0WjU220zhUxbCC3znHQzfJ2lb5Pv6xiObLQxoWGGI8hvFCBq5C8Ge46oNudqdEG9y7aHyQqGpctavCO6LnibMV3EyiyAU13_FBf96W45Qn6o7Tp8V6-fEhA2EMwurjUdqu2IE1j0rufiGRS0jXn-SO0NvPzVGvDlVpM8th2jX-Pq3fK2tYDu94EruuLZNqJF-4m4HftKEjqmnd4UDIAEgK_JoGcxrNxDiY_c9VMW6h_r0DvcOmXT7RseK0s5IigeOZp7rZLcVdEHIYGsUUxrYFdpTmRijgwSQk3ip6XDA
@namespace = default
@tenantName = tenant-test

#=====KAMAJI API=====#

### Get secret 
GET https://{{kamajiServer}}/api/v1/namespaces/{{namespace}}/secrets/{{tenantName}}-admin-kubeconfig
Authorization: Bearer {{accessToken}}
Content-Type: application/json

#data."admin.conf" > base64 > KUBECONFIG

### GET CERTIFICATE CA
GET https://{{kamajiServer}}/api/v1/namespaces/{{namespace}}/secrets/tenant-test-ca
Authorization: Bearer {{accessToken}}
Content-Type: application/json

#.data."tls.crt" > base64 > CA_CERT con qui fare hash per il token di join 

# kubeadm join 172.30.232.66:6443 --token 00fe2f.764c8a2371aebfd2 --discovery-token-ca-cert-hash sha256:d900d6f505f17569537b03fe8bec8b67f1d051886c918c50c19e25d988ecdce6

#===========================================

@proxmoxHost = 172.30.232.90:8006
@nodeName = pve
@vmIdToClone = 10002
@vmId = 20001
@storageName = local-lvm
@user = root
@realm = pam
@tokenId = auth
@secret = afa83fd6-215e-4a13-b6dd-d05ea54a54ab
@authToken = {{user}}@{{realm}}!{{tokenId}}={{secret}}
@username = ubuntu
@password = Testudo123!
@name = test-clone-vm3


#=====PROXMOX API=====#

### Clone VM
POST https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu/{{vmIdToClone}}/clone
Authorization: PVEAPIToken={{authToken}}
Content-Type: application/x-www-form-urlencoded

newid={{vmId}}&full=1&storage={{storageName}}&name={{name}}


### start
POST https://{{proxmoxHost}}/api2/extjs/nodes/{{nodeName}}/qemu/{{vmId}}/status/start
Authorization: PVEAPIToken={{authToken}}

### stop
POST https://{{proxmoxHost}}/api2/extjs/nodes/{{nodeName}}/qemu/{{vmId}}/status/stop
Authorization: PVEAPIToken={{authToken}}

### template


### upload cloud init ??????


### set cloud init 


### start
POST https://{{proxmoxHost}}/api2/extjs/nodes/{{nodeName}}/qemu/{{vmId}}/status/start
Authorization: PVEAPIToken={{authToken}}
