@kamajiServer = 172.30.232.61:6443
@accessToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IlFIdVRkcmRSMEZ3cWp6TGVNSEZJQ0VidS1mZlI0YTBBNmlrYXVkUFNqc3MifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQzNDEwMDUyLCJpYXQiOjE3NDM0MDY0NTIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYjUwNzFkYmItNmIxYi00ZmFhLWExMjctN2FkN2E3OTRkZGZjIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhcGktYWNjZXNzIiwidWlkIjoiMTNjYTM5ZTctOThlZS00YjAzLTk4ZWQtMjQ3MzI4MWM2NTQzIn19LCJuYmYiOjE3NDM0MDY0NTIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphcGktYWNjZXNzIn0.siGRiiW0X7j3iQfEb9eiVLpB381yeWqnfUVY-0j-dwnr_eUeED-pHtxVPoDxGH-g0V0Kjgl67GxxmiZOydkta4d-WZzJQ7PnseOpQtXsOKkfh8GGB3pJVOqvajAMRC9BBtYY0-UuGvSd6tekXyagniJYE5udRIS97SfbLLhKpgg_v3xO1TtnFW7vlBZEMghZ3ip1mcRyRZclkD3T7pxJIWM7w2GCwS-VtcFm5aa1IuLd_-7zHDi9VQAAyvHveAxFB8_mSJ4dqWuStdXZkq5ULUKEflIJtqaN6WVmXAmf6v2v3i-Y4LMxI-sYUVLm5fkVvAJi8MN7Lr4WMMGXvLmXfA
@namespace = default
@tcpName = tenant-test

### Creazione TCP
POST https://{{kamajiServer}}/apis/kamaji.clastix.io/v1alpha1/namespaces/{{namespace}}/tenantcontrolplanes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

< ./createTCP.json

### Eliminazione TCP
DELETE https://{{kamajiServer}}/apis/kamaji.clastix.io/v1alpha1/namespaces/{{namespace}}/tenantcontrolplanes/{{tcpName}}
Authorization: Bearer {{accessToken}}

### Aggiornamento TCP - Modifica Repliche
PATCH https://{{kamajiServer}}/apis/kamaji.clastix.io/v1alpha1/namespaces/{{namespace}}/tenantcontrolplanes/{{tcpName}}
Authorization: Bearer {{accessToken}}
Content-Type: application/merge-patch+json

{
    "spec": {
        "controlPlane": {
            "deployment": {
                "replicas": 3
            }
        }
    }
}

### Aggiornamento TCP - Sostituzione Completa
PUT https://{{kamajiServer}}/apis/kamaji.clastix.io/v1alpha1/namespaces/{{namespace}}/tenantcontrolplanes/{{tcpName}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

< ./tenantcontrolplane.json

### Lista TCP
GET https://{{kamajiServer}}/apis/kamaji.clastix.io/v1alpha1/namespaces/{{namespace}}/tenantcontrolplanes
Authorization: Bearer {{accessToken}}

### Dettagli TCP Specifico
GET https://{{kamajiServer}}/apis/kamaji.clastix.io/v1alpha1/namespaces/{{namespace}}/tenantcontrolplanes/{{tcpName}}
Authorization: Bearer {{accessToken}}

### Lista Deployments
GET https://{{kamajiServer}}/apis/apps/v1/namespaces/{{namespace}}/deployments
Authorization: Bearer {{accessToken}}

### Lista Pods
GET https://{{kamajiServer}}/api/v1/namespaces/{{namespace}}/pods
Authorization: Bearer {{accessToken}}

### Lista Services
GET https://{{kamajiServer}}/api/v1/namespaces/{{namespace}}/services
Authorization: Bearer {{accessToken}}

### Lista Nodes
GET https://{{kamajiServer}}/api/v1/nodes
Authorization: Bearer {{accessToken}}