@proxmoxHost = 172.30.232.90:8006
@nodeName = pve
@vmId = 20002
@newVmId = 10001
@storageName = local-lvm
@user = root
@realm = pam
@tokenId = auth
@secret = afa83fd6-215e-4a13-b6dd-d05ea54a54ab
@authToken = {{user}}@{{realm}}!{{tokenId}}={{secret}}

### Lista Nodi
GET https://{{proxmoxHost}}/api2/json/nodes
Authorization: PVEAPIToken={{authToken}}

### Lista Vm su Nodo
GET https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu
Authorization: PVEAPIToken={{authToken}}

### Informazioni VM - Config
GET https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu/{{vmId}}/config
Authorization: PVEAPIToken={{authToken}}

### Informazioni VM - Status
GET https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu/{{vmId}}/status
Authorization: PVEAPIToken={{authToken}}

### Creazione VM
# vmid esistente -> errore 500
POST https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu
Authorization: PVEAPIToken={{authToken}}
Content-Type: application/x-www-form-urlencoded

vmid={{vmId}}&cores=2&memory=4096

### Eliminazione VM
DELETE https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu/{{vmId}}
Authorization: PVEAPIToken={{authToken}}

### Modifica Configurazione VM
GET https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu/{{vmId}}/config
Authorization: PVEAPIToken={{authToken}}
Content-Type: application/x-www-form-urlencoded
###
cores=2&memory=8192&cicustom=vendor=NFS-SHARE:snippets/cloud-init-test1.yaml&username=provaCustomUser&passwors=Testudo123!


### Start VM
POST https://{{proxmoxHost}}/api2/extjs/nodes/{{nodeName}}/qemu/{{vmId}}/status/start
Authorization: PVEAPIToken={{authToken}}

### Stop VM
POST https://{{proxmoxHost}}/api2/extjs/nodes/{{nodeName}}/qemu/{{vmId}}/status/stop
Authorization: PVEAPIToken={{authToken}}

### Reset VM
POST https://{{proxmoxHost}}/api2/extjs/nodes/{{nodeName}}/qemu/{{vmId}}/status/reset
Authorization: PVEAPIToken={{authToken}}

### Clonazione VM
POST https://{{proxmoxHost}}/api2/json/nodes/{{nodeName}}/qemu/{{vmId}}/clone
Authorization: PVEAPIToken={{authToken}}
Content-Type: application/x-www-form-urlencoded

newid={{newVmId}}&full=1&storage={{storageName}}

### Status VM Corrente
GET https://{{proxmoxHost}}/api2/extjs/nodes/{{nodeName}}/qemu/{{vmId}}/status/current
Authorization: PVEAPIToken={{authToken}}

### Metriche Cluster
GET https://{{proxmoxHost}}/api2/extjs/cluster/resources?type=vm
Authorization: PVEAPIToken={{authToken}}
